MLX90614 Class Reference
Public Types
enum tempUnit_t { MLX90614_TK,
MLX90614_TC,
MLX90614_TF
 }
enum tempSrc_t { MLX90614_SRCA,
MLX90614_SRC01,
MLX90614_SRC02
 }
Public Member Functions
MLX90614 (uint8_t i2caddr=MLX90614_I2CDEFAULTADDR)
MLX90614 Device class constructor.
boolean begin ()
Initialize the device and the i2c interface.
boolean isReady (void)
uint64_t readID (void)
Retrieve the chip ID bytes.
uint8_t getIIRcoeff (void)
Get the coefficients of the IIR digital filter.
uint8_t getFIRcoeff (void)
Get the coefficients of the FIR digital filter.
float getEmissivity (void)
Get the emissivity of the object.
void setIIRcoeff (uint8_t csb=4)
Set the coefficients of the IIR digital filter.
void setFIRcoeff (uint8_t csb=7)
Set the coefficients of the FIR digital filter.
void setEmissivity (float emiss=1.0)
Set the emissivity of the object.
uint16_t readEEProm (uint8_t)
Return a 16 bit value read from EEPROM.
void writeEEProm (uint8_t, uint16_t)
Write a 16 bit value to EEPROM after first clearing the memory.
double readTemp (tempSrc_t=MLX90614_SRC01, tempUnit_t=MLX90614_TC)
Return a temperature from the specified source in specified units.
double convKtoC (double)
Convert temperature in degrees K to degrees C.
double convCtoF (double)
Convert temperature in degrees C to degrees F.
Public Attributes
Property< uint8_t, MLX90614 > busAddr
Property< uint8_t, MLX90614 > rwError
Property< uint8_t, MLX90614 > crc8
Property< uint8_t, MLX90614 > pec
Private Member Functions
uint16_t read16 (uint8_t)
Return a 16 bit value read from RAM or EEPROM.
void write16 (uint8_t, uint16_t)
Write a 16 bit value to memory.
uint8_t getRwError (void)
uint8_t getCRC8 (void)
uint8_t getPEC (void)
uint8_t getAddr (void)
Return the device SMBus address.
void setAddr (uint8_t)
Set device SMBus address.
Private Attributes
boolean _ready
uint8_t _addr
uint8_t _rwError
uint8_t _crc8
uint8_t _pec
Detailed Description
Definition at line 104 of file MLX90614.h.
Member Enumeration Documentation
tempSrc_t
enum MLX90614::tempSrc_t
Enumerations for temperature measurement source.
Enumerator
MLX90614_SRCA Chip (ambient) sensor
MLX90614_SRC01 IR source #1
MLX90614_SRC02 IR source #2
Definition at line 134 of file MLX90614.h.
       :
    boolean _ready;
tempUnit_t
enum MLX90614::tempUnit_t
Enumerations for temperature units.
Enumerator
MLX90614_TK degrees Kelvin
MLX90614_TC degrees Centigrade
MLX90614_TF degrees Fahrenheit
Definition at line 129 of file MLX90614.h.
                    {MLX90614_SRCA, /**< Chip (ambient) sensor */
                     MLX90614_SRC01, /**< IR source #1 */
Constructor & Destructor Documentation
MLX90614()
MLX90614::MLX90614 (uint8_t i2caddr = MLX90614_I2CDEFAULTADDR)
MLX90614 Device class constructor.
Parameters
in i2caddr Device address (default: published value).
Definition at line 46 of file MLX90614.cpp.
References _addr, busAddr, crc8, getAddr(), getCRC8(), getPEC(), getRwError(), pec, rwError, and setAddr().
                                  {
    busAddr.Set_Class(this);
    busAddr.Set_Get(&MLX90614::getAddr);
    busAddr.Set_Set(&MLX90614::setAddr);
    rwError.Set_Class(this);
    rwError.Set_Get(&MLX90614::getRwError);
    pec.Set_Class(this);
    pec.Set_Get(&MLX90614::getPEC);
    crc8.Set_Class(this);
    crc8.Set_Get(&MLX90614::getCRC8);
    _addr = i2caddr;
    _ready = false;
}
Member Function Documentation
convCtoF()
double MLX90614::convCtoF (double degC)
Convert temperature in degrees C to degrees F.
Parameters
in degC Temperature in degrees Centigrade.
Returns
Temperature in degrees Fahrenheit.
Definition at line 389 of file MLX90614.cpp.
Referenced by readTemp().
{return (degC * 1.8) + 32.0;}
convKtoC()
double MLX90614::convKtoC (double degK)
Convert temperature in degrees K to degrees C.
Parameters
in degK Temperature in degrees Kelvin.
Returns
Temperature in degrees Centigrade.
Definition at line 382 of file MLX90614.cpp.
Referenced by readTemp().
{return degK - 273.15;}
getAddr()
uint8_t MLX90614::getAddr (void) [private]
Return the device SMBus address.
SMB bus address getter
Remarks
Must be only device on the bus.
Sets the library to use the new found address.
Returns
Device address.
Definition at line 250 of file MLX90614.cpp.
References _addr, _rwError, and readEEProm().
Referenced by MLX90614().
                              {
    uint8_t tempAddr = _addr;
    _rwError = 0;
    // It is assumed we do not know the existing slave address so the broadcast address is used.
    // This will throw a r/w error so errors will be ignored.
    _addr = MLX90614_BROADCASTADDR;
    // Reload program copy with the existing slave address.
    _addr = lowByte(readEEProm(MLX90614_ADDR));
    return _addr;
}
getCRC8()
uint8_t MLX90614::getCRC8 (void) [inline], [private]
8 bit CRC getter
Definition at line 154 of file MLX90614.h.
Referenced by MLX90614().
getEmissivity()
float MLX90614::getEmissivity (void)
Get the emissivity of the object.
Emissivity getter
Remarks
The emissivity is stored as a 16 bit integer defined by the following:
emissivity = dec2hex[round(65535 x emiss)]
Returns
Physical emissivity value in range 0.1 ...1.0
Definition at line 120 of file MLX90614.cpp.
References _rwError, and readEEProm().
                                  {
    _rwError = 0;
    uint16_t emiss = readEEProm(MLX90614_EMISS);
    if(_rwError) return (float)1.0;
    return (float)emiss / 65535.0;
}
getFIRcoeff()
uint8_t MLX90614::getFIRcoeff (void)
Get the coefficients of the FIR digital filter.
IIR coefficient getter
Remarks
The FIR digital filter coefficient N is bits 10:8 of ConfigRegister1
 The value of N is set as follows: N = 2 ^ (csb + 3)
 The manufacturer does not recommend N < 128
Definition at line 208 of file MLX90614.cpp.
References _rwError, and readEEProm().
                                  {
    _rwError = 0;
    // Get the current value of ConfigRegister1 bits 10:8
    uint8_t fir = (readEEProm(MLX90614_CONFIG) >> 8) & 7;
    if(_rwError) return 7;
    return fir;
}
getIIRcoeff()
uint8_t MLX90614::getIIRcoeff (void)
Get the coefficients of the IIR digital filter.
IIR coefficient getter
Remarks
The IIR digital filter coefficients are set by the LS 3 bits of ConfigRegister1
Returns
Filter coefficient table index. Range 0...7
Definition at line 166 of file MLX90614.cpp.
References _rwError, and readEEProm().
                                  {
    _rwError = 0;
    // Get the current value of ConfigRegister1 bits 2:0
    uint8_t iir = readEEProm(MLX90614_CONFIG) & 7;
    if(_rwError) return 4;
    return iir;
}
getPEC()
uint8_t MLX90614::getPEC (void) [inline], [private]
PEC getter
Definition at line 155 of file MLX90614.h.
Referenced by MLX90614().
getRwError()
uint8_t MLX90614::getRwError (void) [inline], [private]
R/W error flags getter
Definition at line 153 of file MLX90614.h.
Referenced by MLX90614().
read16()
uint16_t MLX90614::read16 (uint8_t cmd) [private]
Return a 16 bit value read from RAM or EEPROM.
Parameters
in cmd Command to send (register to read from).
Returns
Value read from memory.
Definition at line 270 of file MLX90614.cpp.
References _addr, _crc8, _pec, _rwError, and CRC8::crc8().
Referenced by readEEProm(), readTemp(), and writeEEProm().
                                     {
    uint16_t val;
    CRC8 crc(MLX90614_CRC8POLY);
    // Send the slave address then the command and set any error status bits returned by the write.
    Wire.beginTransmission(_addr);
    Wire.write(cmd);
    _rwError |= (1 << Wire.endTransmission(false)) >> 1;
    // Experimentally determined delay to prevent read errors (manufacturer's data sheet has
    // left something out).
    delayMicroseconds(MLX90614_XDLY);
    // Resend slave address then get the 3 returned bytes.
    Wire.requestFrom(_addr, (uint8_t)3);
    // Data is returned as 2 bytes little endian.
    val = Wire.read();
    val |= Wire.read() << 8;
    // Rread the PEC (CRC-8 of all bytes).
    _pec = Wire.read();
    // Clear r/w errors if using broadcast address.
    if(_addr == MLX90614_BROADCASTADDR) _rwError &= MLX90614_NORWERROR;
    
    // Build our own CRC-8 of all received bytes.
    crc.crc8(_addr << 1);
    crc.crc8(cmd);
    crc.crc8((_addr << 1) + 1);
    crc.crc8(lowByte(val));
    _crc8 = crc.crc8(highByte(val));
    // Set error status bit if CRC mismatch.
    if(_crc8 != _pec) _rwError |= MLX90614_RXCRC;
    return val;
}
readEEProm()
uint16_t MLX90614::readEEProm (uint8_t addr)
Return a 16 bit value read from EEPROM.
Parameters
in addr Register address to read from.
Returns
Value read from EEPROM.
Definition at line 344 of file MLX90614.cpp.
References read16().
Referenced by getAddr(), getEmissivity(), getFIRcoeff(), getIIRcoeff(), readID(), setFIRcoeff(), and setIIRcoeff().
{return read16(addr | 0x20);}
readID()
uint64_t MLX90614::readID (void)
Retrieve the chip ID bytes.
Chip ID getter
Returns
Chip ID as a 64 bit word.
Definition at line 395 of file MLX90614.cpp.
References readEEProm().
                              {
    uint64_t ID = 0;
    // If we are lucky the compiler will optimise this.
    for(uint8_t i = 0; i < 4; i++) ID = (ID <<= 16) | readEEProm(MLX90614_ID1 + i);
    return ID;
}
readTemp()
double MLX90614::readTemp (tempSrc_t tsrc = MLX90614_SRC01, tempUnit_t tunit = MLX90614_TC)
Return a temperature from the specified source in specified units.
Remarks
Temperature is stored in ram as a 16 bit absolute value to a resolution of 0.02K
Linearized sensor die temperature is available as Ta (ambient).
One or two object temperatures are linearized to the range -38.2C...125C
Parameters
in tsrc Internal temperature source to read, default #1.
in tunit Temperature units to convert raw data to, default deg Celsius.
Returns
Temperature.
Definition at line 84 of file MLX90614.cpp.
References _rwError, convCtoF(), convKtoC(), MLX90614_SRC01, MLX90614_SRC02, MLX90614_TC, MLX90614_TF, and read16().
                                                          {
    double temp;
    _rwError = 0;
    switch(tsrc) {
        case MLX90614_SRC01 : temp = read16(MLX90614_TOBJ1); break;
        case MLX90614_SRC02 : temp = read16(MLX90614_TOBJ2); break;
        default : temp = read16(MLX90614_TA);
    }
    temp *= 0.02;
    switch(tunit) {
        case MLX90614_TC : return convKtoC(temp);
        case MLX90614_TF : return convKtoC(convCtoF(temp));
    }
    return temp;
}
setAddr()
void MLX90614::setAddr (uint8_t addr) [private]
Set device SMBus address.
SMB bus address setter
Remarks
Must be only device on the bus.
Must power cycle the device after changing address.
Parameters
in addr New device address. Range 1...127
Definition at line 226 of file MLX90614.cpp.
References _addr, _rwError, and writeEEProm().
Referenced by MLX90614().
                                   {
    _rwError = 0;
    // It is assumed we do not know the existing slave address so the broadcast address is used.
    // First ensure the new address is in the legal range (1..127)
    if(addr &= 0x7f) {
        _addr = MLX90614_BROADCASTADDR;
        writeEEProm(MLX90614_ADDR, addr);
        
        // There will always be a r/w error using the broadcast address so we cannot respond
        // to r/w errors. We must just assume this worked.
        _addr = addr;
        
    } else _rwError |= MLX90614_INVALIDATA;
}
setEmissivity()
void MLX90614::setEmissivity (float emiss = 1.0)
Set the emissivity of the object.
Emissivity setter
Remarks
The emissivity is stored as a 16 bit integer defined by the following:
emissivity = dec2hex[round(65535 x emiss)]
Parameters
in emiss Physical emissivity value in range 0.1 ...1.0, default 1.0
Definition at line 107 of file MLX90614.cpp.
References _rwError, and writeEEProm().
                                        {
    _rwError = 0;
    uint16_t e = int(emiss * 65535. + 0.5);
    if((emiss > 1.0) || (e < 6553)) _rwError |= MLX90614_INVALIDATA;
    else writeEEProm(MLX90614_EMISS, e);
}
setFIRcoeff()
void MLX90614::setFIRcoeff (uint8_t csb = 7)
Set the coefficients of the FIR digital filter.
IIR coefficient setter
Remarks
The FIR digital filter coefficient N is bits 10:8 of ConfigRegister1
 The value of N is set as follows: N = 2 ^ (csb + 3)
 The manufacturer does not recommend N < 128
Parameters
in csb See page 12 of datasheet. Range 0...7, default = 7 (N = 1024)
Definition at line 184 of file MLX90614.cpp.
References _rwError, readEEProm(), and writeEEProm().
                                      {
    _rwError = 0;
    // Ensure legal range by clearing all but the LS 3 bits.
    csb &= 7;
    // Get the current value of ConfigRegister1
    uint16_t reg = readEEProm(MLX90614_CONFIG);
    // Clear bits 10:8, mask in the new value, then write it back.
    if(!_rwError) {
        reg &= 0xf8ff;
        reg |= (uint16_t)csb << 8;
        writeEEProm(MLX90614_CONFIG, reg);
    }
}
setIIRcoeff()
void MLX90614::setIIRcoeff (uint8_t csb = 4)
Set the coefficients of the IIR digital filter.
IIR coefficient setter
Remarks
The IIR digital filter coefficients are set by the LS 3 bits of ConfigRegister1
 The value of the coefficients is set as follows:
csb = 0   a1 = 0.5    a2 = 0.5
      1        0.25        0.75
      2        0.167       0.833
      3        0.125       0.875
      4        1           0 (IIR bypassed)
      5        0.8         0.2
      6        0.67        0.33
      7        0.57        0.43 
Parameters
in csb See page 12 of datasheet. Range 0...7, default = 4 (IIR bypassed)
Definition at line 143 of file MLX90614.cpp.
References _rwError, readEEProm(), and writeEEProm().
                                      {
    _rwError = 0;
    // Ensure legal range by clearing all but the LS 3 bits.
    csb &= 7;
    // Get the current value of ConfigRegister1
    uint16_t reg = readEEProm(MLX90614_CONFIG);
    // Clear bits 2:0, mask in the new value, then write it back.
    if(!_rwError) {
        reg &= 0xfff8;
        reg |= (uint16_t)csb;
        writeEEProm(MLX90614_CONFIG, reg);
    }
}
write16()
void MLX90614::write16 (uint8_t cmd, uint16_t data) [private]
Write a 16 bit value to memory.
Parameters
in cmd Command to send (register to write to).
in data Value to write.
Definition at line 314 of file MLX90614.cpp.
References _addr, _crc8, _pec, _rwError, and CRC8::crc8().
Referenced by writeEEProm().
                                                 {
    CRC8 crc(MLX90614_CRC8POLY);
    // Build the CRC-8 of all bytes to be sent.
    crc.crc8(_addr << 1);
    crc.crc8(cmd);
    crc.crc8(lowByte(data));
    _crc8 = crc.crc8(highByte(data));
    // Send the slave address then the command.
    Wire.beginTransmission(_addr);
    Wire.write(cmd);
    // Write the data low byte first.
    Wire.write(lowByte(data));
    Wire.write(highByte(data));
    // Then write the crc and set the r/w error status bits.
    Wire.write(_pec = _crc8);
    _rwError |= (1 << Wire.endTransmission(true)) >> 1;
    // Clear r/w errors if using broadcast address.
    if(_addr == MLX90614_BROADCASTADDR) _rwError &= MLX90614_NORWERROR;
}
writeEEProm()
void MLX90614::writeEEProm (uint8_t reg, uint16_t data)
Write a 16 bit value to EEPROM after first clearing the memory.
Remarks
Erase and write time 5ms per manufacturer specification
Manufacturer does not specify max or min erase/write times
Parameters
in reg Address to write to.
in data Value to write.
Definition at line 354 of file MLX90614.cpp.
References _rwError, read16(), and write16().
Referenced by setAddr(), setEmissivity(), setFIRcoeff(), and setIIRcoeff().
                                                     {
    uint16_t val;
    reg |= 0x20;
    // Read current value, compare to the new value, and do nothing on a match or if there are
    // read errors set the error status flag only.
    val = read16(reg);
    if((val != data) && !_rwError) {
        // On any R/W errors it is assumed the memory is corrupted.
        // Clear the memory and wait Terase (per manufacturer's documentation).
        write16(reg, 0);
        delay(5);
        if(_rwError) _rwError |= MLX90614_EECORRUPT;
        // Write the data and wait Twrite (per manufacturer's documentation)
        // and set the r/w error status bits.
        write16(reg, data);
        delay(5);
        if(_rwError) _rwError |= MLX90614_EECORRUPT;
    }
}
Member Data Documentation
_addr
uint8_t MLX90614::_addr [private]
Slave address
Definition at line 145 of file MLX90614.h.
Referenced by getAddr(), MLX90614(), read16(), setAddr(), and write16().
_crc8
uint8_t MLX90614::_crc8 [private]
8 bit CRC
Definition at line 147 of file MLX90614.h.
Referenced by begin(), read16(), and write16().
_pec
uint8_t MLX90614::_pec [private]
PEC
Definition at line 148 of file MLX90614.h.
Referenced by begin(), read16(), and write16().
_rwError
uint8_t MLX90614::_rwError [private]
R/W error flags
Definition at line 146 of file MLX90614.h.
Referenced by begin(), getAddr(), getEmissivity(), getFIRcoeff(), getIIRcoeff(), read16(), readTemp(), setAddr(), setEmissivity(), setFIRcoeff(), setIIRcoeff(), write16(), and writeEEProm().
busAddr
Property<uint8_t, MLX90614> MLX90614::busAddr
SMBus address property
Definition at line 123 of file MLX90614.h.
Referenced by MLX90614().
crc8
Property<uint8_t, MLX90614> MLX90614::crc8
8 bit CRC property
Definition at line 125 of file MLX90614.h.
Referenced by MLX90614().
pec
Property<uint8_t, MLX90614> MLX90614::pec
PEC property
Definition at line 126 of file MLX90614.h.
Referenced by MLX90614().
rwError
Property<uint8_t, MLX90614> MLX90614::rwError
R/W error flags property
Definition at line 124 of file MLX90614.h.
Referenced by MLX90614().
The documentation for this class was generated from the following files:
MLX90614.h
MLX90614.cpp