CRC8 Class Reference
Public Member Functions
CRC8 (uint8_t polynomial=CRC8_DEFAULTPOLY)
CRC8 class constructor.
uint8_t crc8 (void)
Return the current value of the CRC.
uint8_t crc8 (uint8_t data)
Update the current value of the CRC.
void crc8Start (uint8_t poly)
Initialize the CRC8 object.
Private Attributes
uint8_t _crc
uint8_t _poly
Detailed Description
Definition at line 37 of file Crc8.h.
Constructor & Destructor Documentation
CRC8()
CRC8::CRC8 (uint8_t poly = CRC8_DEFAULTPOLY)
CRC8 class constructor.
Parameters
in poly 8 bit CRC polynomial to use.
Definition at line 36 of file Crc8.cpp.
References crc8Start().
{crc8Start(poly);}
Member Function Documentation
crc8() [1/2]
uint8_t CRC8::crc8 (void)
Return the current value of the CRC.
Returns
8 bit CRC current value.
Definition at line 42 of file Crc8.cpp.
Referenced by MLX90614::read16(), and MLX90614::write16().
{return _crc;}
crc8() [2/2]
uint8_t CRC8::crc8 (uint8_t data)
Update the current value of the CRC.
Parameters
in data New 8 bit data to be added to the CRC.
Returns
8 bit CRC current value.
Definition at line 49 of file Crc8.cpp.
                               {
    uint8_t i = 8;
    
    _crc ^= data;
    while(i--) _crc = _crc & 0x80 ? (_crc << 1) ^ _poly : _crc << 1;
    return _crc;
}
crc8Start()
void CRC8::crc8Start (uint8_t poly)
Initialize the CRC8 object.
Parameters
in poly 8 bit CRC polynomial to use.
Definition at line 61 of file Crc8.cpp.
Referenced by CRC8().
                                 {
    _poly = poly;
    _crc = 0;
}
The documentation for this class was generated from the following files:
Crc8.h
Crc8.cpp